### ISSUE TITLE
Strong Wolfe Conditions

### ISSUE THREAD

**Issue by tolgabirdal** [NicolasBoumal/manopt#10]
Nicolas,

First thanks for building ManOpt. It's just great. I have been looking into the source code, but could not figure out whether the strong Wolfe conditions are employed at any stage/version of the line search algorithms. As far as I know, this is essential for achieving descent in the L-BFGS algorithm. Or are there other line-search methods in ManOpt that can ensure this?

All the best,

**Comment by NicolasBoumal** [comment]
Hello Tolga,

You are correct: we do not have code for line-search ensuring strong Wolfe conditions. In particular, the solver `rbfgs`, which is a limited-memory version of Riemannian BFGS, uses a backtracking line-search, satisfying the simpler Armijo condition.

If you implement a line-search function that guarantees strong Wolfe, it'd be great if you could contribute it to the toolbox.

Best,
Nicolas

**Comment by tolgabirdal** [comment]
Nicolas,

Good to know. Sure I'll do that once I have the time. In the meanwhile, I was wondering whether just like the Euclidean case, the Riemannian LBFGS requires the strong Wolfe to guarantee the convergence (or descent) or not. Are you aware of any paper proving this?

Cheers,

**Comment by NicolasBoumal** [comment]
Hello Tolga,

Off the top of my head I do not know what the theoretical requirements are for LBFGS. I'd imagine this can be found for example in Nocedal and Wright's book.

I do remember that when using BFGS to optimize nonsmooth cost functions, it is important to (1) use full BFGS (not limited memory), and (2) to ensure strong Wolfe conditions.

Best,
Nicolas

**Comment by NicolasBoumal** [comment]
(Closing for now as this was inactive for a while, but happy to re-open it later.)
