### ISSUE TITLE
Optimize parallel transport on positive matrices

### ISSUE THREAD

**Issue by kellertuer** [NicolasBoumal/manopt#30]
I just notices that the parallel transport on the positive numbers, see

https://github.com/NicolasBoumal/manopt/blob/116fbae4db137236be747d439a81b11feddabbea/manopt/manifolds/positive/positivefactory.m#L132-L135

can be optimised: Since that is an element wise operation, the multiplication commutes and can just be done by

````matlab
    function zeta = parallel_transport(X, Y, eta)
        zeta = eta.*Y./X;
    end
````

and could maybe even set as default?

**Comment by NicolasBoumal** [comment]
Indeed, I'll push that change now; thanks!
