### ISSUE TITLE
M.vec in fixedTTrankfactory "index out of bounds"

### ISSUE THREAD

**Issue by NicolasBoumal** [NicolasBoumal/manopt#33]
The following code fails:
```
M = fixedTTrankfactory([2 2 2 2], [1 2 2 2 1]);
X = M.rand()
V = M.randvec(X)
v = M.vec(X, V) % fails
```

with the follow error message:
```
Index exceeds the number of array elements (4).
Error in fixedTTrankfactory/vec (line 277)
            ind_step = numel(Z.dU{index}); 
```

**Comment by mpsenka21** [comment]
Hello Nicolas,

Thank you for raising this. There were a couple of trivial bugs involving the indexing in M.vec for fixedTTrankfactory.

I have rebased my fork and pushed an update that fixes M.vec, which now runs as intended on my machine; also, is this the best way for me to push future changes?

Best,
Michael
