### ISSUE TITLE
TTeMPS tensorprod now collides with R2022a builtin

### ISSUE THREAD

**Issue by djoshea** [NicolasBoumal/manopt#44]
Hello, thanks so much for your work on Manopt! 

Minor issue - the function `tensorprod` inside the `ttfixedrank/TTeMPS_1.1` folder now collides with the new R2022a built-in [ https://www.mathworks.com/help/matlab/ref/tensorprod.html ].

I'd be happy to submit a PR with all the references renamed to something. Perhaps `tt_tensorprod` or `tensormatrixprod`?

Thanks!
Dan

**Comment by NicolasBoumal** [comment]
Hello Dan,
Thanks for bringing this up! I was not aware of it.
I renamed tensorprod to tensorprod_ttemps (so both appear as suggestions when hitting "tab").
Can you pull the latest version of the code and let me know if this works for you?
Best,
Nicolas

**Comment by djoshea** [comment]
Looks good to me! I unfortunately don't have any specific examples using ttfixedrank, but low_rank_tensor_completion_TT runs fine for me now, and tensorprod now refers to the built-in again.

Thanks!
Dan

**Comment by djoshea** [comment]
Leaving a note that Nicolas fixed this in [40cd4a6](https://github.com/NicolasBoumal/manopt/commit/40cd4a696e256d31f4ecbd5436699b1bb2fcb3cc).
